// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/mitkimi/Documents/develop/opensource/ApronDesign/react/node_modules/dumi/theme-default/slots/RtlSwitch/index.js';
