// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from 'D:/OPENSOURCE/apron.design/react/.dumi/pages/_layout.tsx?type=frontmatter';
import { frontmatter as fm1, toc as t1 } from 'D:/OPENSOURCE/apron.design/react/.dumi/pages/index.tsx?type=frontmatter';
import { frontmatter as fm2, toc as t2 } from 'D:/OPENSOURCE/apron.design/react/docs/components/responsive-modal.md?type=frontmatter';
import { demoIndex as dmi2 } from 'D:/OPENSOURCE/apron.design/react/docs/components/responsive-modal.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from 'D:/OPENSOURCE/apron.design/react/docs/components/datepicker.md?type=frontmatter';
import { demoIndex as dmi3 } from 'D:/OPENSOURCE/apron.design/react/docs/components/datepicker.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from 'D:/OPENSOURCE/apron.design/react/docs/components/pagination.md?type=frontmatter';
import { demoIndex as dmi4 } from 'D:/OPENSOURCE/apron.design/react/docs/components/pagination.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from 'D:/OPENSOURCE/apron.design/react/docs/components/cascader.md?type=frontmatter';
import { demoIndex as dmi5 } from 'D:/OPENSOURCE/apron.design/react/docs/components/cascader.md?type=demo-index';
import { frontmatter as fm6, toc as t6 } from 'D:/OPENSOURCE/apron.design/react/docs/components/checkbox.md?type=frontmatter';
import { demoIndex as dmi6 } from 'D:/OPENSOURCE/apron.design/react/docs/components/checkbox.md?type=demo-index';
import { frontmatter as fm7, toc as t7 } from 'D:/OPENSOURCE/apron.design/react/docs/components/collapse.md?type=frontmatter';
import { demoIndex as dmi7 } from 'D:/OPENSOURCE/apron.design/react/docs/components/collapse.md?type=demo-index';
import { frontmatter as fm8, toc as t8 } from 'D:/OPENSOURCE/apron.design/react/docs/components/inputotp.md?type=frontmatter';
import { demoIndex as dmi8 } from 'D:/OPENSOURCE/apron.design/react/docs/components/inputotp.md?type=demo-index';
import { frontmatter as fm9, toc as t9 } from 'D:/OPENSOURCE/apron.design/react/docs/components/skeleton.md?type=frontmatter';
import { demoIndex as dmi9 } from 'D:/OPENSOURCE/apron.design/react/docs/components/skeleton.md?type=demo-index';
import { frontmatter as fm10, toc as t10 } from 'D:/OPENSOURCE/apron.design/react/docs/components/timeline.md?type=frontmatter';
import { demoIndex as dmi10 } from 'D:/OPENSOURCE/apron.design/react/docs/components/timeline.md?type=demo-index';
import { frontmatter as fm11, toc as t11 } from 'D:/OPENSOURCE/apron.design/react/docs/components/divider.md?type=frontmatter';
import { demoIndex as dmi11 } from 'D:/OPENSOURCE/apron.design/react/docs/components/divider.md?type=demo-index';
import { frontmatter as fm12, toc as t12 } from 'D:/OPENSOURCE/apron.design/react/docs/components/message.md?type=frontmatter';
import { demoIndex as dmi12 } from 'D:/OPENSOURCE/apron.design/react/docs/components/message.md?type=demo-index';
import { frontmatter as fm13, toc as t13 } from 'D:/OPENSOURCE/apron.design/react/docs/components/popover.md?type=frontmatter';
import { demoIndex as dmi13 } from 'D:/OPENSOURCE/apron.design/react/docs/components/popover.md?type=demo-index';
import { frontmatter as fm14, toc as t14 } from 'D:/OPENSOURCE/apron.design/react/docs/components/tooltip.md?type=frontmatter';
import { demoIndex as dmi14 } from 'D:/OPENSOURCE/apron.design/react/docs/components/tooltip.md?type=demo-index';
import { frontmatter as fm15, toc as t15 } from 'D:/OPENSOURCE/apron.design/react/docs/components/avatar.md?type=frontmatter';
import { demoIndex as dmi15 } from 'D:/OPENSOURCE/apron.design/react/docs/components/avatar.md?type=demo-index';
import { frontmatter as fm16, toc as t16 } from 'D:/OPENSOURCE/apron.design/react/docs/components/button.md?type=frontmatter';
import { demoIndex as dmi16 } from 'D:/OPENSOURCE/apron.design/react/docs/components/button.md?type=demo-index';
import { frontmatter as fm17, toc as t17 } from 'D:/OPENSOURCE/apron.design/react/docs/components/drawer.md?type=frontmatter';
import { demoIndex as dmi17 } from 'D:/OPENSOURCE/apron.design/react/docs/components/drawer.md?type=demo-index';
import { frontmatter as fm18, toc as t18 } from 'D:/OPENSOURCE/apron.design/react/docs/components/select.md?type=frontmatter';
import { demoIndex as dmi18 } from 'D:/OPENSOURCE/apron.design/react/docs/components/select.md?type=demo-index';
import { frontmatter as fm19, toc as t19 } from 'D:/OPENSOURCE/apron.design/react/docs/components/switch.md?type=frontmatter';
import { demoIndex as dmi19 } from 'D:/OPENSOURCE/apron.design/react/docs/components/switch.md?type=demo-index';
import { frontmatter as fm20, toc as t20 } from 'D:/OPENSOURCE/apron.design/react/docs/components/alert.md?type=frontmatter';
import { demoIndex as dmi20 } from 'D:/OPENSOURCE/apron.design/react/docs/components/alert.md?type=demo-index';
import { frontmatter as fm21, toc as t21 } from 'D:/OPENSOURCE/apron.design/react/docs/components/badge.md?type=frontmatter';
import { demoIndex as dmi21 } from 'D:/OPENSOURCE/apron.design/react/docs/components/badge.md?type=demo-index';
import { frontmatter as fm22, toc as t22 } from 'D:/OPENSOURCE/apron.design/react/docs/components/empty.md?type=frontmatter';
import { demoIndex as dmi22 } from 'D:/OPENSOURCE/apron.design/react/docs/components/empty.md?type=demo-index';
import { frontmatter as fm23, toc as t23 } from 'D:/OPENSOURCE/apron.design/react/docs/components/image.md?type=frontmatter';
import { demoIndex as dmi23 } from 'D:/OPENSOURCE/apron.design/react/docs/components/image.md?type=demo-index';
import { frontmatter as fm24, toc as t24 } from 'D:/OPENSOURCE/apron.design/react/docs/components/index.md?type=frontmatter';
import { demoIndex as dmi24 } from 'D:/OPENSOURCE/apron.design/react/docs/components/index.md?type=demo-index';
import { frontmatter as fm25, toc as t25 } from 'D:/OPENSOURCE/apron.design/react/docs/components/input.md?type=frontmatter';
import { demoIndex as dmi25 } from 'D:/OPENSOURCE/apron.design/react/docs/components/input.md?type=demo-index';
import { frontmatter as fm26, toc as t26 } from 'D:/OPENSOURCE/apron.design/react/docs/components/modal.md?type=frontmatter';
import { demoIndex as dmi26 } from 'D:/OPENSOURCE/apron.design/react/docs/components/modal.md?type=demo-index';
import { frontmatter as fm27, toc as t27 } from 'D:/OPENSOURCE/apron.design/react/docs/components/radio.md?type=frontmatter';
import { demoIndex as dmi27 } from 'D:/OPENSOURCE/apron.design/react/docs/components/radio.md?type=demo-index';
import { frontmatter as fm28, toc as t28 } from 'D:/OPENSOURCE/apron.design/react/docs/components/space.md?type=frontmatter';
import { demoIndex as dmi28 } from 'D:/OPENSOURCE/apron.design/react/docs/components/space.md?type=demo-index';
import { frontmatter as fm29, toc as t29 } from 'D:/OPENSOURCE/apron.design/react/docs/components/steps.md?type=frontmatter';
import { demoIndex as dmi29 } from 'D:/OPENSOURCE/apron.design/react/docs/components/steps.md?type=demo-index';
import { frontmatter as fm30, toc as t30 } from 'D:/OPENSOURCE/apron.design/react/docs/components/toast.md?type=frontmatter';
import { demoIndex as dmi30 } from 'D:/OPENSOURCE/apron.design/react/docs/components/toast.md?type=demo-index';
import { frontmatter as fm31, toc as t31 } from 'D:/OPENSOURCE/apron.design/react/docs/components/card.md?type=frontmatter';
import { demoIndex as dmi31 } from 'D:/OPENSOURCE/apron.design/react/docs/components/card.md?type=demo-index';
import { frontmatter as fm32, toc as t32 } from 'D:/OPENSOURCE/apron.design/react/docs/components/form.md?type=frontmatter';
import { demoIndex as dmi32 } from 'D:/OPENSOURCE/apron.design/react/docs/components/form.md?type=demo-index';
import { frontmatter as fm33, toc as t33 } from 'D:/OPENSOURCE/apron.design/react/docs/components/grid.md?type=frontmatter';
import { demoIndex as dmi33 } from 'D:/OPENSOURCE/apron.design/react/docs/components/grid.md?type=demo-index';
import { frontmatter as fm34, toc as t34 } from 'D:/OPENSOURCE/apron.design/react/docs/components/link.md?type=frontmatter';
import { demoIndex as dmi34 } from 'D:/OPENSOURCE/apron.design/react/docs/components/link.md?type=demo-index';
import { frontmatter as fm35, toc as t35 } from 'D:/OPENSOURCE/apron.design/react/docs/components/rate.md?type=frontmatter';
import { demoIndex as dmi35 } from 'D:/OPENSOURCE/apron.design/react/docs/components/rate.md?type=demo-index';
import { frontmatter as fm36, toc as t36 } from 'D:/OPENSOURCE/apron.design/react/docs/components/spin.md?type=frontmatter';
import { demoIndex as dmi36 } from 'D:/OPENSOURCE/apron.design/react/docs/components/spin.md?type=demo-index';
import { frontmatter as fm37, toc as t37 } from 'D:/OPENSOURCE/apron.design/react/docs/components/tabs.md?type=frontmatter';
import { demoIndex as dmi37 } from 'D:/OPENSOURCE/apron.design/react/docs/components/tabs.md?type=demo-index';
import { frontmatter as fm38, toc as t38 } from 'D:/OPENSOURCE/apron.design/react/docs/components/tag.md?type=frontmatter';
import { demoIndex as dmi38 } from 'D:/OPENSOURCE/apron.design/react/docs/components/tag.md?type=demo-index';
import { frontmatter as fm39, toc as t39 } from 'D:/OPENSOURCE/apron.design/react/docs/index.md?type=frontmatter';
import { demoIndex as dmi39 } from 'D:/OPENSOURCE/apron.design/react/docs/index.md?type=demo-index';
import { frontmatter as fm40, toc as t40 } from 'D:/OPENSOURCE/apron.design/react/docs/demo.md?type=frontmatter';
import { demoIndex as dmi40 } from 'D:/OPENSOURCE/apron.design/react/docs/demo.md?type=demo-index';

export const filesMeta = {
  '_layout': {
    frontmatter: fm0,
    toc: t0,
  },
  'index': {
    frontmatter: fm1,
    toc: t1,
  },
  'docs/components/responsive-modal': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/responsive-modal.md?type=text'),
  },
  'docs/components/datepicker': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/datepicker.md?type=text'),
  },
  'docs/components/pagination': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/pagination.md?type=text'),
  },
  'docs/components/cascader': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/cascader.md?type=text'),
  },
  'docs/components/checkbox': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/checkbox.md?type=text'),
  },
  'docs/components/collapse': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/collapse.md?type=text'),
  },
  'docs/components/inputotp': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/inputotp.md?type=text'),
  },
  'docs/components/skeleton': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/skeleton.md?type=text'),
  },
  'docs/components/timeline': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/timeline.md?type=text'),
  },
  'docs/components/divider': {
    frontmatter: fm11,
    toc: t11,
    demoIndex: dmi11,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/divider.md?type=text'),
  },
  'docs/components/message': {
    frontmatter: fm12,
    toc: t12,
    demoIndex: dmi12,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/message.md?type=text'),
  },
  'docs/components/popover': {
    frontmatter: fm13,
    toc: t13,
    demoIndex: dmi13,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/popover.md?type=text'),
  },
  'docs/components/tooltip': {
    frontmatter: fm14,
    toc: t14,
    demoIndex: dmi14,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/tooltip.md?type=text'),
  },
  'docs/components/avatar': {
    frontmatter: fm15,
    toc: t15,
    demoIndex: dmi15,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/avatar.md?type=text'),
  },
  'docs/components/button': {
    frontmatter: fm16,
    toc: t16,
    demoIndex: dmi16,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/button.md?type=text'),
  },
  'docs/components/drawer': {
    frontmatter: fm17,
    toc: t17,
    demoIndex: dmi17,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/drawer.md?type=text'),
  },
  'docs/components/select': {
    frontmatter: fm18,
    toc: t18,
    demoIndex: dmi18,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/select.md?type=text'),
  },
  'docs/components/switch': {
    frontmatter: fm19,
    toc: t19,
    demoIndex: dmi19,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/switch.md?type=text'),
  },
  'docs/components/alert': {
    frontmatter: fm20,
    toc: t20,
    demoIndex: dmi20,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/alert.md?type=text'),
  },
  'docs/components/badge': {
    frontmatter: fm21,
    toc: t21,
    demoIndex: dmi21,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/badge.md?type=text'),
  },
  'docs/components/empty': {
    frontmatter: fm22,
    toc: t22,
    demoIndex: dmi22,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/empty.md?type=text'),
  },
  'docs/components/image': {
    frontmatter: fm23,
    toc: t23,
    demoIndex: dmi23,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/image.md?type=text'),
  },
  'docs/components/index': {
    frontmatter: fm24,
    toc: t24,
    demoIndex: dmi24,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/index.md?type=text'),
  },
  'docs/components/input': {
    frontmatter: fm25,
    toc: t25,
    demoIndex: dmi25,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/input.md?type=text'),
  },
  'docs/components/modal': {
    frontmatter: fm26,
    toc: t26,
    demoIndex: dmi26,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/modal.md?type=text'),
  },
  'docs/components/radio': {
    frontmatter: fm27,
    toc: t27,
    demoIndex: dmi27,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/radio.md?type=text'),
  },
  'docs/components/space': {
    frontmatter: fm28,
    toc: t28,
    demoIndex: dmi28,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/space.md?type=text'),
  },
  'docs/components/steps': {
    frontmatter: fm29,
    toc: t29,
    demoIndex: dmi29,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/steps.md?type=text'),
  },
  'docs/components/toast': {
    frontmatter: fm30,
    toc: t30,
    demoIndex: dmi30,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/toast.md?type=text'),
  },
  'docs/components/card': {
    frontmatter: fm31,
    toc: t31,
    demoIndex: dmi31,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/card.md?type=text'),
  },
  'docs/components/form': {
    frontmatter: fm32,
    toc: t32,
    demoIndex: dmi32,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/form.md?type=text'),
  },
  'docs/components/grid': {
    frontmatter: fm33,
    toc: t33,
    demoIndex: dmi33,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/grid.md?type=text'),
  },
  'docs/components/link': {
    frontmatter: fm34,
    toc: t34,
    demoIndex: dmi34,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/link.md?type=text'),
  },
  'docs/components/rate': {
    frontmatter: fm35,
    toc: t35,
    demoIndex: dmi35,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/rate.md?type=text'),
  },
  'docs/components/spin': {
    frontmatter: fm36,
    toc: t36,
    demoIndex: dmi36,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/spin.md?type=text'),
  },
  'docs/components/tabs': {
    frontmatter: fm37,
    toc: t37,
    demoIndex: dmi37,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/tabs.md?type=text'),
  },
  'docs/components/tag': {
    frontmatter: fm38,
    toc: t38,
    demoIndex: dmi38,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/components/tag.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm39,
    toc: t39,
    demoIndex: dmi39,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/index.md?type=text'),
  },
  'docs/demo': {
    frontmatter: fm40,
    toc: t40,
    demoIndex: dmi40,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/OPENSOURCE/apron.design/react/docs/demo.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
